backend:
  name: github
  branch: master
  repo: Will-Mann-16/PersonalWebsite

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    files: 
      - name: 'about'
        label: 'About'
        file: 'src/content/about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Content', name: 'content', widget: 'markdown' }
      - name: 'projects'
        label: 'Projects'
        file: 'src/content/projects.md'
        fields:
          - label: 'Projects'
            name: 'Projects'
            widget: 'list'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
              - { label: 'Completed', name: 'completed', widget: 'boolean' }
              - { label: 'Languages', name: 'languages', widget: 'list' }
              - { label: 'Description', name: 'description', widget: 'markdown' }
      